<?php
/**
 * Front to the WordPress application. This file doesn't do anything, but loads
 * wp-blog-header.php which tells WordPress to load the theme.
 *
 * @package WordPress
 *
 * DO NOT EDIT THIS FILE.
 *
 * This file is copied into this location from vendor/humanmade/local-vip on
 * `composer install`. It is based on the core WordPress index.php file.
 *
 * phpcs:disable PSR1.Files.SideEffects
 */

/**
 * Tells WordPress to load the WordPress theme and output it.
 *
 * @var bool
 */
define( 'WP_USE_THEMES', true );


/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/wordpress/wp-blog-header.php' );
